name: List Project V2 IDs

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  list-projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.TRUNKTOPUS_APP_ID }}
          private-key: ${{ secrets.TRUNKTOPUS_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Show organization projects
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          ORGANIZATION_NAME: "${{ github.repository_owner }}"
        run: |
          set -e
          
          echo "🔍 Projects for organization: $ORGANIZATION_NAME"
          gh api graphql -f query='
            query($login: String!) {
              organization(login: $login) {
                projectsV2(first: 50) {
                  nodes {
                    id
                    title
                    url
                  }
                }
              }
            }' \
            -f login="$ORGANIZATION_NAME"